### ISSUE TITLE
ログイン失敗時の処理修正

### ISSUE THREAD

**Issue by s-iritani** [minmin0530/chat#41]
ログインを失敗した時に「Cannot GET /views/login」が表示されてしまいます。

「index.js」の「res.redirect('/views/login?login_error')」の記述ですが、
このよう「res.redirect('/login?login_error')」に修正した方が良さそうですがいかがでしょうか。

**Comment by minmin0530** [comment]
はい、その `res.redirect('/login?login_error')` に修正お願いします。

**Comment by s-iritani** [comment]
ソースがマージされましたのでクローズします。
